<a href="https://colab.research.google.com/github/jwalith/Exposis/blob/main/Exposis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/50_Startups.csv")

In [ ]:
dnup = data.to_numpy()

In [ ]:
data.shape

(50, 4)

In [ ]:
dnup


array([[165349.2 , 136897.8 , 471784.1 , 192261.83],
       [162597.7 , 151377.59, 443898.53, 191792.06],
       [153441.51, 101145.55, 407934.54, 191050.39],
       [144372.41, 118671.85, 383199.62, 182901.99],
       [142107.34,  91391.77, 366168.42, 166187.94],
       [131876.9 ,  99814.71, 362861.36, 156991.12],
       [134615.46, 147198.87, 127716.82, 156122.51],
       [130298.13, 145530.06, 323876.68, 155752.6 ],
       [120542.52, 148718.95, 311613.29, 152211.77],
       [123334.88, 108679.17, 304981.62, 149759.96],
       [101913.08, 110594.11, 229160.95, 146121.95],
       [100671.96,  91790.61, 249744.55, 144259.4 ],
       [ 93863.75, 127320.38, 249839.44, 141585.52],
       [ 91992.39, 135495.07, 252664.93, 134307.35],
       [119943.24, 156547.42, 256512.92, 132602.65],
       [114523.61, 122616.84, 261776.23, 129917.04],
       [ 78013.11, 121597.55, 264346.06, 126992.93],
       [ 94657.16, 145077.58, 282574.31, 125370.37],
       [ 91749.16, 114175.79, 294919.57, 12426

In [ ]:
dnup.shape

(50, 4)

In [ ]:
type(dnup)

numpy.ndarray

In [ ]:
train = dnup[0:40]

In [ ]:
test = dnup[40:]

In [ ]:
train.shape

(40, 4)

In [ ]:
train_features = train[:,0:-1]
train_label =train[:,-1]

In [ ]:
train_features.shape

(40, 3)

In [ ]:
test_features = test[:,0:-1]
test_label =test[:,-1]

In [ ]:
train_features[0].shape

(3,)

In [ ]:
train_label.shape

(40,)

In [ ]:
from tensorflow.keras.models import Sequential

In [ ]:
from tensorflow.keras.layers import Input, Dense, Dropout

In [ ]:
model = Sequential()
model.add(Input(shape=(3,)))
model.add(Dense(6,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3,activation='relu'))
model.add(Dropout(0.2))
#model.add(Dense(1,activation='sigmoid'))
model.add(Dense(16,activation='relu'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 24        
                                                                 
 dropout (Dropout)           (None, 6)                 0         
                                                                 
 dense_1 (Dense)             (None, 3)                 21        
                                                                 
 dropout_1 (Dropout)         (None, 3)                 0         
                                                                 
 dense_2 (Dense)             (None, 16)                64        
                                                                 
Total params: 109
Trainable params: 109
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='adam', loss = 'mse' )

In [ ]:
model.fit(train_features,train_label,epochs=50,validation_data=(test_features,test_label))

Epoch 1/50
2/2 [==============================] - 1s 225ms/step - loss: 10796898304.0000 - val_loss: 2638673152.0000
Epoch 2/50
2/2 [==============================] - 0s 45ms/step - loss: 11084426240.0000 - val_loss: 2629728768.0000
Epoch 3/50
2/2 [==============================] - 0s 50ms/step - loss: 10891905024.0000 - val_loss: 2620542464.0000
Epoch 4/50
2/2 [==============================] - 0s 44ms/step - loss: 10766624768.0000 - val_loss: 2610861056.0000
Epoch 5/50
2/2 [==============================] - 0s 43ms/step - loss: 10687145984.0000 - val_loss: 2601601536.0000
Epoch 6/50
2/2 [==============================] - 0s 67ms/step - loss: 10713033728.0000 - val_loss: 2591845376.0000
Epoch 7/50
2/2 [==============================] - 0s 71ms/step - loss: 10994526208.0000 - val_loss: 2582600192.0000
Epoch 8/50
2/2 [==============================] - 0s 47ms/step - loss: 10427567104.0000 - val_loss: 2573993472.0000
Epoch 9/50
2/2 [==============================] - 0s 41ms/step - loss: 

In [ ]:
model.save('startup.h5')

In [ ]:
pwd

'/content'

**1.Linear Regression**

In [ ]:
from sklearn import linear_model

In [ ]:
reg = linear_model.LinearRegression()

In [ ]:
data.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [ ]:
Features = ['R&D Spend','Administration','Marketing Spend']

In [ ]:
reg.fit(data[['R&D Spend','Administration','Marketing Spend']], data.Profit)

LinearRegression()

In [ ]:
reg.coef_


array([ 0.80571505, -0.02681597,  0.02722806])

In [ ]:
reg.intercept_

50122.19298986524

In [ ]:
reg.predict([(142107.34	,91391.77,366168.42)])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([172139.51418327])

In [ ]:
x =data[Features]

In [ ]:
y=data['Profit']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
linreg = LinearRegression()

In [ ]:
linreg.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_linpred = linreg.predict(x_test)

In [ ]:
from sklearn import metrics

In [ ]:
print(metrics.mean_squared_error(y_test,y_linpred))

71775956.57202546


In [ ]:
 from sklearn.metrics import mean_squared_error,mean_absolute_error,median_absolute_error,max_error
 print(mean_squared_error(y_test,y_linpred))
 print(mean_absolute_error(y_test, y_linpred))
 print(median_absolute_error(y_test, y_linpred))
 print(max_error(y_test, y_linpred))

71775956.57202546
7027.308813746572
6348.404585115495
16715.356954255825


In [ ]:
linreg.score(x_test,y_test)


0.9314223105185139

**2.GradientBoostingRegressor**

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
grad = GradientBoostingRegressor(random_state=0)
grad.fit(x_train, y_train)



GradientBoostingRegressor(random_state=0)

In [ ]:
grad.score(x_test, y_test)

0.8825757847803504

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
gradc = GradientBoostingRegressor(random_state=0)
gradc.fit(x_train, y_train)

GradientBoostingRegressor(random_state=0)

In [ ]:
gradc.score(x_test, y_test)

0.8825757847803504

In [ ]:
y_gradcpred = gradc.predict(x_test)
print(metrics.mean_squared_error(y_test,y_gradcpred))
print(mean_absolute_error(y_test, y_gradcpred))
print(median_absolute_error(y_test, y_gradcpred))
print(max_error(y_test, y_gradcpred))

122900544.41663724
8710.873649108735
7755.665232503539
25187.081950317603


**3.RandomForest**

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
fore = RandomForestRegressor(max_depth=2, random_state=0)
fore.fit(x_train, y_train)

RandomForestRegressor(max_depth=2, random_state=0)

In [ ]:
fore.score(x_test, y_test)

0.8367063873230725

In [ ]:
y_forepred = fore.predict(x_test)
print(metrics.mean_squared_error(y_test,y_forepred))
print(mean_absolute_error(y_test, y_forepred))
print(median_absolute_error(y_test, y_forepred))
print(max_error(y_test, y_forepred))

170909159.24124983
9659.599128229118
12392.202829321788
30156.977939991048


4.**SVM**

In [ ]:
from sklearn.svm import LinearSVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [ ]:
sv = make_pipeline(StandardScaler(),LinearSVR(random_state=0, tol=1e-5))

In [ ]:
sv.fit(x_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearsvr', LinearSVR(random_state=0, tol=1e-05))])

In [ ]:
sv.score(x_test, y_test)

-15.240953285060417

In [ ]:
y_svpred = sv.predict(x_test)
print(metrics.mean_squared_error(y_test,y_svpred))
print(mean_absolute_error(y_test, y_svpred))
print(median_absolute_error(y_test, y_svpred))
print(max_error(y_test, y_svpred))

16998384846.306273
126300.22846153844
111276.02
191013.39


**5.Bayesian Regression** 

In [ ]:
breg = linear_model.BayesianRidge()
breg.fit(x_train, y_train)

BayesianRidge()

In [ ]:
breg.score(x_test, y_test)

0.931317688217324

In [ ]:
y_bregpred = breg.predict(x_test)
print(metrics.mean_squared_error(y_test,y_bregpred))
print(mean_absolute_error(y_test, y_bregpred))
print(median_absolute_error(y_test, y_bregpred))
print(max_error(y_test, y_bregpred))

71885458.15779555
7085.534942154918
6334.663074654702
16445.74936419756


**6.Polynomial regression**

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline

In [ ]:
poly = PolynomialFeatures(degree=2)
pmodel = Pipeline([('poly', PolynomialFeatures(degree=3)), ('linear', LinearRegression(fit_intercept=False))])
pmodel.fit(x_train, y_train)

Pipeline(steps=[('poly', PolynomialFeatures(degree=3)),
                ('linear', LinearRegression(fit_intercept=False))])

In [ ]:
pmodel.score(x_test, y_test)

-0.07871394316844516

In [ ]:
y_pmodelpred = pmodel.predict(x_test)
print(metrics.mean_squared_error(y_test,y_pmodelpred))
print(mean_absolute_error(y_test, y_pmodelpred))
print(median_absolute_error(y_test, y_pmodelpred))
print(max_error(y_test, y_pmodelpred))

1129022072.978986
24115.372320450137
17268.758719553516
79261.52465314214
